### ISSUE TITLE
Bai index warning sometimes unnecessary 

### ISSUE THREAD

**Issue by charlesgregory** [blachlylab/dhtslib#100]
This warning is reported anytime a `SAMReader` is opened on a sam file or a bam file without an index.  We should consider only retrieving an index when the `query` methods are used. So that this error is not issued when a index is not being used. 
```
[E::idx_find_and_load] Could not retrieve index file for 'test.bam'
```

**Comment by jblachly** [comment]
agree; plus it should be a warning not an error
