### ISSUE TITLE
Isolate coordinates.d

### ISSUE THREAD

**Issue by charlesgregory** [blachlylab/dhtslib#104]
As suggested by Arne Ludwig [here](https://forum.dlang.org/post/duzdclxvvrifoastdztv@forum.dlang.org) it could be advantageous to separate `coordinates.d` into its own module and remove `htslib` dependencies.

**Comment by jblachly** [comment]
Please also work on mkaing the other corrections he noted

**Comment by jblachly** [comment]
I'll put your paper on arXiv.org once this is taken care of
