### ISSUE TITLE
SAMRecord sequence could be rev comp'd

### ISSUE THREAD

**Issue by charlesgregory** [blachlylab/dhtslib#13]
When returning the sequence from SAMRecord, it is reverse complemented if the ```BAM_FREVERSE``` flag has been set. Why? This is counter to how ```samtools view``` would display the reads. Samtools always displays the read to match the reference (i.e. if read maps to minus strand will be represented as plus strand). This breaks the assumption that reads are always shown as plus strand unless unmapped which the SAM format specifies. Also, we would have to reverse the cigar string to match (we currently don't). Is this a bug?

https://github.com/blachlylab/dhtslib/blob/66e8700c113dea5c83d6cadd901e61bc2f71bc69/source/dhtslib/sam.d#L115-L132

We do the same thing with the qscores.
https://github.com/blachlylab/dhtslib/blob/66e8700c113dea5c83d6cadd901e61bc2f71bc69/source/dhtslib/sam.d#L133-L152

**Comment by charlesgregory** [comment]
Accidentally pushed changes to develop branch that fix this in commit 3a22f03. We can revert after we discuss the issue if needed.

**Comment by charlesgregory** [comment]
Fixing this appears to have fixed my issues with the Hotspotter output on branch polytyper_merge.

**Comment by jblachly** [comment]
You are absolutely correct, this is my mistake -- I was working on uBAM support at the time; this would have been correct representation for decomposing back to original input reads. Great find.
