### ISSUE TITLE
Convenience functions needed for SAMRecord 

### ISSUE THREAD

**Issue by charlesgregory** [blachlylab/dhtslib#17]
Since most of these should just be direct references to the bam1_t or bam1_core_t, should we inline most of these? Will we have a function call for just returning a value? I assume yes.

**Comment by jblachly** [comment]
Yes, please `pragma(inline,true)`.

Test with DMD as well as LDC. Ideally also test with GDC.  If any compiler cannot inline, version() the pragma so that the other compiler(s) can still be directed to inline.  DMD in particular has trouble inlining some things / is not as advanced.

**Comment by jblachly** [comment]
I added the rest of `bam1_core_t`

Would be nice to also return contig name as a string but would be slower
