### ISSUE TITLE
htslib 1.10 compatibility

### ISSUE THREAD

**Issue by jblachly** [blachlylab/dhtslib#35]

**Comment by jblachly** [comment]
- [X] bgzf.d
- [X] faidx.d
- [X] hfile.d
- [X] hts.d
- [ ] hts_log.d
- [ ] kstring.d
- [ ] regidx.d
- [ ] sam.d
- [x] tbx.d
- [x] thread_pool.d
- [ ] vcf.d

**Comment by jblachly** [comment]
@charlesgregory I am almost done with bindings, only lacking sam.d (huge but am halfway through) and regidx.d (very short). 

Can you start working on some tests for 1.10 , in the 1.10 branch?

**Comment by jblachly** [comment]
and perhaps as important, looking at the SAMreader, vcfreader, etc. interfaces in `dhtslib` namespace ? hopefully all that shoudl be urgent is changing the coordinate to 64 bits.

tons of new function in htslib-1.10 `sam.h` which probably we built by hand in SAMReader/Writer already

**Comment by charlesgregory** [comment]
Yep I'll start testing on the 1.10 branch

**Comment by jblachly** [comment]
regidx and sam upgraded via dstep (tragically losing a lot of our manual doc comments)

**Comment by jblachly** [comment]
# machine assisted conversion (dstep)

- [ ] bgzf.h
- [ ] cram.h
- [ ] faidx.h
- [ ] hfile.h
- [ ] hts_defs.h
- [ ] hts_endian.h
- [ ] hts.h
- [ ] hts_log.h
- [ ] hts_os.h
- [ ] kbitset.h
- [ ] kfunc.h
- [ ] khash.h
- [ ] khash_str2int.h
- [ ] klist.h
- [ ] knetfile.h
- [ ] kseq.h
- [ ] ksort.h
- [ ] kstring.h
- [x] regidx.h
- [x] sam.h
- [ ] synced_bcf_reader.h
- [ ] tbx.h
- [ ] thread_pool.h
- [ ] vcf.h
- [ ] vcf_sweep.h
- [ ] vcfutils.h

**Comment by jblachly** [comment]
As of today we have 1.10 version for all of our previous header wrappers, 4 of which were dstep converted; and in addition added cram.h

OK to merge develop into master, then htslib-1.10 into develop

Will keep this tracking issue open for now

**Comment by charlesgregory** [comment]
We may need to go through machine converted macros as ```bam_get_cigar``` wasn't converted correctly.
The conversion shown below casts b.data to a ```uint *``` incorrectly and then adds ```b.core.l_qname```;
Pointer arithmetic would mean our pointer moves ```b.core.l_qname``` * 4 bytes since our b.data is now a uint pointer.
```
extern (D) auto bam_get_cigar(T)(auto ref T b)
{
    return cast(uint*) b.data + b.core.l_qname;
}
```
Changing the function back to our original hand translation fixes the issue with proper parentheses and casting only the final result of the pointer arithmetic. Pointer arithmetic would mean our pointer moves ```b.core.l_qname``` bytes since our b.data is still a ubyte pointer.
```
extern (D) auto bam_get_cigar(bam1_t * b)
{
    return cast(uint*) ((*b).data + (*b).core.l_qname);
}
```

Our cigar unittests caught this.

**Comment by charlesgregory** [comment]
Other than the ```bam_get_cigar``` issue, the unittests are passing.

**Comment by jblachly** [comment]
A+ for unit testing, I wish I had discovered them earlier in life

Can you write more tests to exercise other corners of the code?

**Comment by jblachly** [comment]
@charlesgregory We need to pull the trigger on merging develop in to master at some point. Can you try compiling all your client programs public and non public with `develop` and htslib 1.10 ?

1.11 is already out ...

**Comment by charlesgregory** [comment]
We need to resolve #52 first, but yes I think we should. Will we update the sematic versioning to 2.x after this with all the api changes?

**Comment by jblachly** [comment]
we are at 0.10.x.
I am thinking 0.11.0+htslib-1.10, or perhaps 1.0.0+htslib-1.10

**Comment by jblachly** [comment]
With 5f93e381d7ab284543a6e960c5cf2c7a3d7a5afd , we can begin tracking automated conversions which will facilitate much easier upgrade bindings to newest version (1.11 is already out ... )

**Comment by jblachly** [comment]
@charlesgregory It was time to officially supprt htslib-1.10, given it is a year old and 1.11 is out now. Merged to master. Will keep this tracking issue open , and once all .h files switched to automated conversion will change issue to reflect 1.11

**Comment by jblachly** [comment]
`tbx.d` contains at least one error (int instead of long param to `tbx_itr_queryi`) ; needs machine assisted conversion

**Comment by charlesgregory** [comment]
I have actually fixed these in the htslib112 branch.
