### ISSUE TITLE
Segfault in certain situations involving cigar

### ISSUE THREAD

**Issue by charlesgregory** [blachlylab/dhtslib#40]
It appears that in certain situations interacting with the cigar can lead to a segfault. I experienced this in ldc 1.20, only when building in release mode.
```
foreach (SAMRecord read; bam.all_records)
{
    /// do something with record
    Cigar cigar = read.cigar;
    auto cigar_ops = cigar.ops; //cigar.ops is a slice to the original cigar data 
    
    /// SAMRecord reaped here?
    /// do something with cigar_ops -> segfault
}
```
Sometimes in the above situation, I think the SAMRecord will be reaped before we are done using the cigar data. The cigar is simply a slice to the data allocated by htslib to the cigar array. The easy fix for this is below; we simply duplicate the cigar before use.
```
auto cigar_ops = cigar.ops.dup;
```
Potentially we should modify the ```cigar()``` method in ```SAMRecord``` to always duplicate the original cigar data rather than return a slice.

**Comment by jblachly** [comment]
Shouldn’t `Cigar cigar = read.cigar` just make a copy from `read` ?
If not, would doing that solve it?

**Comment by charlesgregory** [comment]
Yes making a copy should solve it as the SAMRecord can be freed if it is no longer needed without causing a segfault when the cigar accesses that data. I had originally avoided the having ```cigar()``` make a copy for performance sake, but I did not foresee this issue.

**Comment by jblachly** [comment]
Looking back at your original example, the `SAMRecord` should never go out of scope until the next iteration and should not be reaped by GC. thus there must be a different problem.

**Comment by jblachly** [comment]
@charlesgregory Any more luck with this?

**Comment by jblachly** [comment]
@charlesgregory ping

**Comment by charlesgregory** [comment]
Honestly I probably need to rework ```cigar.d```. Not drastically but the ```Cigar``` struct should probably own whatever data is under the struct ( a simple ```dup``` in the constructor would suffice). Also some more helper functions, and making iteration easier.

**Comment by jblachly** [comment]
ultimately it woudl be nice to have cigar and md modules under the .sam. namespace. 
we could include (deprecated?) imports at the dhtslib package level for reverse compat
