### ISSUE TITLE
Make Cigar iterable

### ISSUE THREAD

**Issue by jblachly** [blachlylab/dhtslib#44]
(wishlist only)
Evidently there is a generator `CigarItr` which takes cigar struct and makes range, but couldn't we embed range primitives within Cigar itself? would be more ergonomic

**Comment by charlesgregory** [comment]
How should it be iterable? Should we return CigarOps (i.e 6M, 3I, 3D ...)? CigarItr returns a sequence of ops (i.e. 6M3I3D -> M, M, M, M, M, M, I, I, I, D, D, D).

**Comment by jblachly** [comment]
I should be able to do this:

```D
foreach(c; read.cigar) {
    f( c.op );
    g( c.length);
}
```

**Comment by jblachly** [comment]
which is how it works in pysam

**Comment by charlesgregory** [comment]
No my CigarItr returns an Ops enum and repeats until the CigarOp is exhausted.
