### ISSUE TITLE
SAMRecord needs string reference name!

### ISSUE THREAD

**Issue by jblachly** [blachlylab/dhtslib#45]
we have only `@property tid` ; should wrap `sam_hdr_tid2name`

this would mirror `pysam.reference_name`

**Comment by charlesgregory** [comment]
I am unsure of how to approach this. This would require accessing a ```SAMHeader``` or ```SAMReader``` (i.e ```string reference(SAMHeader header);``` ) unless we add it in as the ```SAMRecord``` generated from the ```SAMReader```. Also if the ```SAMRecord``` was generated without a reader, it shouldn't have a string reference name.

**Comment by jblachly** [comment]
Presumably we could just make the SAMRecord constructor take a `sam_hdr_t *` also :

    /// Construct SAMRecord from supplied bam1_t
    this(bam1_t* b)
    {
        //debug(dhtslib_debug) hts_log_debug(__FUNCTION__, "ctor(bam1_t *b)");
        this.b = b;
    }

This will break any client code that constructs a SAMRecord directly although I suspect 99% of use we are receiving a SAMRecord from a query or iterator rather than constructing ourselves.

If you see no problems I will add

**Comment by charlesgregory** [comment]
Yeah this sounds reasonable.

**Comment by jblachly** [comment]
Most addressed in 87a37a831440a557be6690b5249a4f3a58a83c0a

Note that this commit adds a method returning  `const(char)[]` , not `string`
