### ISSUE TITLE
cigar_and_md_api

### ISSUE THREAD

**Issue by jblachly** [blachlylab/dhtslib#51]
Source/network graph does not show that this branch has been merged

https://github.com/blachlylab/dhtslib/commit/0e683c939cb497cc7ae33f45b9a5508c9b9ee105

@charlesgregory 
What's up with this branch?

**Comment by charlesgregory** [comment]
I merged it here: 5f4006efa2f4a2403268bffb6328f6efc7d000c7.

**Comment by jblachly** [comment]
Weird for whatever reason it doesn't show as a merge in the source grph, that branch just kinda stopped.
Can you delete the branch?
