### ISSUE TITLE
htslib submodule is out of date

### ISSUE THREAD

**Issue by charlesgregory** [blachlylab/dhtslib#54]
we should keep this up to date with the current supported/compatible version

**Comment by jblachly** [comment]
I have not used this submodule in any way shape or form; what depends on it?

**Comment by charlesgregory** [comment]
I have used it in the past when statically linking dhtslib. fishnet builds htslib from this submodule.

**Comment by jblachly** [comment]
feel free to update. maybe update documentation with detailed instructions

static linking (usu) still requires libcurl and a number of other libraries to be dynamically linked (ie present on end user system) unless doing a minimal htslib build without S3 support; and even then TRUE static linking (i.e. no dynamic linking including libc) requires a musl-compatible version of phobos which I haven't built and isn't included.

**Comment by jblachly** [comment]
@charlesgregory ping
