### ISSUE TITLE
Should SAMRecord and VCFRecord be struct (currently class)?

### ISSUE THREAD

**Issue by jblachly** [blachlylab/dhtslib#57]
At the risk of breaking some client code, should we consider making `SAMRecord` and `VCFRecord` struct instead of class?

These are typically generated in hot loops as we plow through an NGS file, and stack allocation of structs over heap allocation of classes, with attendant GC, might net huge performance gains for some use cases, while really not being problematic for all other cases.

**Comment by charlesgregory** [comment]
I would prefer structs where possible for potential performance benefits. Though it would be interesting to test some of our other software such as fade or maskerade using structs to see if there are real impacts.

**Comment by charlesgregory** [comment]
So in working on reference counting for ```SAMRecord``` and ```Cigar```, I have found that the postblit constructor ```this(this)``` doesn't work on classes (I forgot). So structs may be required or at least optimal for reference counting as is ```IndexedFastaFile```.

**Comment by jblachly** [comment]
may break clients and our own tests. Note that currently we have a lot of `new SAMRecord`; even if were made structs, woudl go on GC heap. 

If structs, we'll have to scrub the codebase for `new` and make sure stack alloc structs are returned by value

**Comment by charlesgregory** [comment]
partially fixed by 3ceb9523ea501a06ad3f1ee2a10dbd0d603629ef
