### ISSUE TITLE
SAMReader/SAMWriter should store and use SAMHeader

### ISSUE THREAD

**Issue by charlesgregory** [blachlylab/dhtslib#62]

**Comment by charlesgregory** [comment]
Currently they still use ```bam_hdr_t``` pointers.

**Comment by jblachly** [comment]
Agree, but many reader (writer too?) methods depend on having a pointer to the header, and currently this is `private`.

FOr example:

https://github.com/blachlylab/dhtslib/blob/fcb0047b73e1b8c8eef7e9631891272be7597c2d/source/dhtslib/sam/package.d#L955

**Comment by jblachly** [comment]
Also, looking at the code, it's going to be a fair amount of work given the number of reader methods (writer?) that depend on header. Some design decisions will have to be made as well (how many methods should be duplicated in SAMHeader?)

Another thing related to the header pointer is the destroy call in the `SAMReader` (writer?) destructor. Currently no dtor in `SAMHeader` which will lead to dangling pointers.


Finally, we'll also at the same time probably want to break up `package.d` ; should we shoot for one file per class?

**Comment by charlesgregory** [comment]
I think that's a good idea (splitting ```package.d``` up). We should potentially make ```SAMHeader``` own the ```bam_hdr_t``` pointer and deal with it's destruction. May need to reference count though. Would that cause issues with ```SAMRecord``` since it now also takes in a header?

**Comment by jblachly** [comment]
> I think that's a good idea (splitting `package.d` up). We should potentially make `SAMHeader` own the `bam_hdr_t` pointer and deal with it's destruction. May need to reference count though. Would that cause issues with `SAMRecord` since it now also takes in a header?

Yes, possibly. We do want to retain the ability to construct a record independently of a reader/writer (I think?), in which case the record needs a reference to a header. could be a shared ref though, if we use ref counting
