### ISSUE TITLE
Split dhtslib/sam/package.d

### ISSUE THREAD

**Issue by charlesgregory** [blachlylab/dhtslib#63]
Split ```dhtslib/sam/package.d``` into one class/struct per file. This will make the file more manageable. It will also help the classes/structs not be separated by lots of unittests.

**Comment by charlesgregory** [comment]
New structure:
```
dhtslib/sam/package.d -> dhtslib/sam/package.d    (only public imports and helper functions)
                                      -> dhtslib/sam/record.d       SAMRecord
                                      -> dhtslib/sam/reader.d       SAMReader
                                      -> dhtslib/sam/writer.d       SAMWriter
dhtslib/tagvalue.d         -> dhtslib/sam/tagvalue.d
```

**Comment by jblachly** [comment]
Sounds fine, but don't forget that `private` is module-level, be prepared for breakage. Good reason to get the CI tests fixed before undertaking this change
