### ISSUE TITLE
overload opIndex for SAMFile (and others) as de facto query

### ISSUE THREAD

**Issue by jblachly** [blachlylab/dhtslib#7]
Current syntax:

```
auto bam = SAMFile("whatever.bam");
foreach(r; bam.query("chr1:2000-3000");
```

Proposed:
```
auto bam = SAMFile("whatever.bam");
foreach(r; bam["chr1:2000-3000"]);
```

**Comment by jblachly** [comment]
Reopening for discussion as to whether

`[chr, start, pos]` should be deprecated/ removed in favor of `[chr, start .. end ]`

**Comment by jblachly** [comment]
Also, I agree that I like your multidimensional array syntax better than BioD's

**Comment by charlesgregory** [comment]
The ```bam[chr, start, end]``` syntax will be deprecated.
opSlice will be defined to allow for ```bam["chr1", 1..2]``` to work.

**Comment by charlesgregory** [comment]
This has been fixed.
