### ISSUE TITLE
v0.12.2 seems to be incompatible with parallel foreach

### ISSUE THREAD

**Issue by charlesgregory** [blachlylab/dhtslib#70]
When using parallel ```foreach``` in fade with new version of dhtslib, the reference counting ```invariant``` in ```SAMRecord``` gets thrown. Using a normal ```foreach``` loop causes no issues. Unfortunately, this will likely greatly hurt fade's performance. So much for the wonders of reference counting. I may have to come up with a custom parallel aggregate or something. Or perhaps my reference counting implementation is incomplete or not smart enough.

**Comment by charlesgregory** [comment]
It seems removing the invariant in ```SAMRecord``` solves the problem with no segfaulting. Though this is not the way I want to solve this issue. Unless there is a reason the ```refct``` should be able to go below 0.

**Comment by jblachly** [comment]
Refcount should not be below zero.  I would not close this just yet

**Comment by jblachly** [comment]
Oh, I just saw the title. probably the problem  is that parallel foreach is not atomically updating (`--`) the refcount. Although it's a unary op, because it's an `if` statement it has to be executed as at least two  or three separate processor instructions (store/load, , cmp, then decr)

**Comment by charlesgregory** [comment]
Figured it out. Current SAMRecord dtor looks like this:
```
if (--refct == 0 && p_cigar.references == 0 && p_tagval.references == 0)
```
```p_cigar``` and ```p_tagval``` are private ```Cigar``` and ```TagValue```. These help us keep the ```SAMRecord``` around while there is still cigar or tag data being referenced. However I overlooked the fact that this can cause the ```SAMRecord``` ```refct``` to fall below 0 if there are still references to the cigar or tag data.

Changing the dtor to this fixes the issue:
```
if(refct > 0) refct--;
// remove only if no references to this or underlying bam1_t data
if (refct == 0 && p_cigar.references == 0 && p_tagval.references == 0)
          bam_destroy1(this.b); // we created our own in default ctor, or received copy via bam_dup1
```
