### ISSUE TITLE
Rework coordinate shortcuts

### ISSUE THREAD

**Issue by charlesgregory** [blachlylab/dhtslib#81]
Need to have shortcuts for types that are separate from the shortcuts for getting a coordinate type from integer coordinates.
i.e
```{D}
ZBHO coords;
coords =  toZBHO(0, 1);

OneBasedClosed coords2;
coords2 =  toOneBasedClosed(0, 1);
```

Bigger question is what to do about `ChromCoordinates`.
Maybe this:
```{D}
ChromZBHO coords;
coords =  toChromZBHO(0, 1);
```
Thoughts @jblachly ?

**Comment by jblachly** [comment]
I don't understand -- what do the `to*` functions assume is the implicit coordinate scheme of the integer inputs?

**Comment by charlesgregory** [comment]
Yes though the naming is arbitrary it could be `ZBHOfromInt` or something else.
