### ISSUE TITLE
Coordinates ctor for two coordinate isn't used

### ISSUE THREAD

**Issue by charlesgregory** [blachlylab/dhtslib#85]
The below line should cause a compile-time error: 
```
auto coords = Coordinates!(Coordsystem.zbho)(Coordinate!(Basis.one)(1), Coordinate!(Basis.one)(2));
```
It should error because the input `Coordinate`s are required to have the same `Basis` type as the `Coordsystem`:
https://github.com/blachlylab/dhtslib/blob/d5fd711d5d1f1b2b3fb38de3c6dcee15685445aa/source/dhtslib/coordinates.d#L198-L202

Though it doesn't error because of the `alias this` in `Coordinate` which allows them to act as `long`s 
https://github.com/blachlylab/dhtslib/blob/d5fd711d5d1f1b2b3fb38de3c6dcee15685445aa/source/dhtslib/coordinates.d#L62-L67

and `Coordinates` has a `long` ctor, so the specific ctor for two `Coordinate`s is ignored by the compiler:
https://github.com/blachlylab/dhtslib/blob/d5fd711d5d1f1b2b3fb38de3c6dcee15685445aa/source/dhtslib/coordinates.d#L192-L196

My proposed fix is to remove the specific ctor for two `Coordinate`s  from `Coordinates` to prevent confusion.

**Comment by jblachly** [comment]
if you are happy w your fix move it on over into `develop`; what do we lose by dropping `alias this?`

**Comment by charlesgregory** [comment]
if we dropped `alias this` we lose the ability to use a `Coordinate` directly as a `long` i.e. 
```
Coordinate!(Basis.zero) val;
val = 1;
```

**Comment by jblachly** [comment]
That seems like a major loss to me.
Are you sure there aren't any other ways to coerce values?

**Comment by charlesgregory** [comment]
My current solution doesn't drop the `alias this` just the `Coordinates` ctor that accepts two `Coordinate`s which is not necessary.
