### ISSUE TITLE
Test files needed

### ISSUE THREAD

**Issue by charlesgregory** [blachlylab/dhtslib#9]
We need some standard bam, vcf, tabix, etc files added to the repo for testing. This will make testing consistent for the programs in the test folder

**Comment by jblachly** [comment]
I think we can likely commit to using the ones in htslib.
Will leave issue open until tests using local files are converted.

**Comment by jblachly** [comment]
@charlesgregory

**Comment by charlesgregory** [comment]
Closing this as we currently use htslib test files for unittests
