### ISSUE TITLE
dhtslib versioning

### ISSUE THREAD

**Issue by charlesgregory** [blachlylab/dhtslib#93]
I have noticed when you use `dub add` or the `dub init` command to add dhtslib only the initial part of the version gets added.
```
full version: v0.12.4+htslib-1.10
dub added version: v0.12.4
```
Does this matter? Everything compiles fine. Should we make some form of check to ensure your htslib version is minimally supported? This may be a non-issue.

**Comment by jblachly** [comment]
Probably just a dub bug; as long as everything compiles fine I wouldn't worry about it. consider posting on the Dlang forum
