### ISSUE TITLE
Default dub configuration

### ISSUE THREAD

**Issue by charlesgregory** [blachlylab/dhtslib#95]
Building with dhtslib as a dependency leads to the "unittest" configuration being used.  
```
Performing "release" build using ldc2 for x86_64.
dhtslib 0.12.4+htslib-1.10: target for configuration "unittest" is up to date.
```
I think this can be fixed by making the "source" configuration the first configuration.
```
{
     "name": "source",
     "targetType": "library",
     "libs": ["hts"]
},
```

**Comment by jblachly** [comment]
You're probably right. I also just looked at `dub.json` and note that the source-static shoudl probably refer to `htslib/libhts.a` instead of `../htslib/...`
